export {
  Display,
  PageTitle,
  SectionTitle,
  Subtitle,
  BodyText,
  BodyLarge,
  BodySmall,
  HintText,
  HelperText,
  ErrorText,
  Label,
  Caption,
  LinkText,
  ButtonText,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
} from './Typography';
export type { HeadingLevel, HeadingProps } from './Typography';
